# Generated by Django 5.2.3 on 2025-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoarmazenamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
