# Generated by Django 5.2.3 on 2025-09-02 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracaoarmazenamento_ativo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidade',
            field=models.PositiveIntegerField(default=1, help_text='Periodicidade em meses (1 a 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='meta',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='meta',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='preenchimento',
            name='valor_realizado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('master', 'Master'), ('gestor', 'Gestor')], default='gestor', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='permissaoindicador',
            unique_together={('usuario', 'indicador')},
        ),
    ]
