# Generated by Django 5.2.3 on 2025-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_managers_alter_indicador_periodicidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracao',
        ),
        migrations.AlterModelOptions(
            name='logdeacao',
            options={'ordering': ['-data'], 'verbose_name': 'Log de Ação', 'verbose_name_plural': 'Logs de Ações'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.RemoveField(
            model_name='configuracaoarmazenamento',
            name='dia_limite_preenchimento',
        ),
        migrations.AlterField(
            model_name='logdeacao',
            name='acao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logdeacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
