# Generated by Django 5.2.3 on 2025-09-02 14:45

import api.models.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_configuracao_alter_logdeacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', api.models.managers.UsuarioManager()),
            ],
        ),
    ]
