# Generated by Django 5.2.5 on 2025-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_configuracao_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdeacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='permissaoindicador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='dia_limite_preenchimento',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracaoarmazenamento',
            name='dia_limite_preenchimento',
            field=models.PositiveSmallIntegerField(default=10, help_text='Apenas até esse dia do mês os gestores poderão preencher indicadores.', verbose_name='Dia limite para preenchimento'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidade',
            field=models.PositiveIntegerField(default=1, help_text='Periodicidade em meses (1 a 12)'),
        ),
        migrations.AlterField(
            model_name='logdeacao',
            name='acao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logdeacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meta',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preenchimento',
            name='valor_realizado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
