# Generated by Django 5.2.5 on 2025-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_setor_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='mes_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
