# Generated by Django 5.2.5 on 2025-09-18 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_indicador_mes_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preenchimento',
            name='valor_realizado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
