# Generated by Django 5.2.5 on 2025-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_preenchimento_valor_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preenchimento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preenchimento',
            name='valor_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
