# Generated by Django 5.2.5 on 2025-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_align_usuario_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='permitir_editar_meta_gestor',
            field=models.BooleanField(default=False, help_text='Quando ativo, gestores podem editar metas mensais no frontend.'),
        ),
    ]
